Add url in pom.xml
jenkinsci/tfs-plugin pull request #237
Opened 2020-09-24 06:57 UTC by hp77-creator

This is done in process to address the issue opened in [jenkinsci/jenkins.io](https://github.com/jenkins-infra/jenkins.io/issues/3723). Next step is redirection from [here](https://wiki.jenkins.io/display/JENKINS/Azure+DevOps+and+Team+Foundation+Server+Plugin#) to [here](https://plugins.jenkins.io/tfs/).

2020-09-24 12:08 UTC, oleg-nenashev requested changes
Wrong URL is supplied here

2020-09-24 21:37 UTC, hp77-creator commented
Goofed up in copy pasting. Really sorry!

2020-09-27 09:11 UTC, oleg-nenashev approved these changes

2021-02-25 06:41 UTC, hp77-creator commented
@oleg-nenashev  This PR is not merged neither closed? Any updates? tfs plugins is removed from the jenkins so does that mean we don't need this?

2025-01-05 11:06 UTC, closed without merging